#services:  # Defines a collection of services to be created and managed by Docker Compose.
#  database:  # Specifies the database service, in this case, PostgreSQL.
#    image: "postgres:latest"  # Uses the latest version of the official PostgreSQL image from Docker Hub.
#    ports:  # Maps ports between the host machine and the container.
#      - "5432:5432"  # Maps port 5432 on the host to port 5432 in the container (default PostgreSQL port).
#    environment:  # Sets environment variables for configuring the PostgreSQL database.
#      POSTGRES_USER: ${POSTGRES_USER}  # Defines the username for the PostgreSQL database as "admin".
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Sets the password for the PostgreSQL database as "admin".
#      POSTGRES_DB: ${POSTGRES_DB}  # Creates a default PostgreSQL database named "postgres".
#    volumes:  # Defines a volume to persist database data outside the container.
#      - ./database:/var/lib/postgresql/data  # Maps the local `./database` directory to the container's PostgreSQL data directory.
#





services:  # Defines a collection of services to be created and managed by Docker Compose.
  database:  # Specifies the database service, in this case, PostgreSQL.
    image: "postgres:latest"  # Uses the latest version of the official PostgreSQL image from Docker Hub.
    env_file:
      - variables.env
    ports:  # Maps ports between the host machine and the container.
      - "5432:5432"  # Maps port 5432 on the host to port 5432 in the container (default PostgreSQL port).
    volumes:  # Defines a volume to persist database data outside the container.
      - ./database:/var/lib/postgresql/data  # Maps the local `./database` directory to the container's PostgreSQL data directory.
